### ISSUE TITLE
No such file or directory: 'cache/cache-dc-value-tshark-all-raw-dns_ictf2010_deduped-1000.ddc'

### ISSUE THREAD

**Issue by Aaron911** [vs-uulm/nemesys#1]
hi, When I took the file of '/input/dns_ictf2010.pcap' as an example and ran `python nemetyl_align-segments.py dns_ictf2010_deduped-1000.pcap`, this error occurred:
`No such file or directory: 'cache/cache-dc-value-tshark-all-raw-dns_ictf2010_deduped-1000.ddc'`
And, the folders of '/cache/’‘/reports/‘ are always empty during my operation as your README. Can u help me to solve it? Thank u very much.

**Comment by skleber** [comment]
According to the command line you pasted, I assume, you called the script with **src/** being the current directory? That would explain the error, since the cache and reports folders are one directory level up. Please try to call the `python src/nemetyl_align-segments.py input/dns_ictf2010_deduped-100.pcap` (try a shorter trace for starters) from the repositories base directory. 

I definitely need to improve the documentation.

**Comment by Aaron911** [comment]
> According to the command line you pasted, I assume, you called the script with **src/** being the current directory? That would explain the error, since the cache and reports folders are one directory level up. Please try to call the `python src/nemetyl_align-segments.py input/dns_ictf2010_deduped-100.pcap` (try a shorter trace for starters) from the repositories base directory.
> 
> I definitely need to improve the documentation.

hi, skleber. Thank u very much for your reply. I have solved this problem follow your reply. But, I encountered another problem when I tried with my own pcapfile. When I ran `python ./src/check_parse-pcap.py ./mycapfile_deduped-1000.pcap`, I got the error as follows many many times:
```
Current message: [1607051670.418707 4c:02:a9:e0:5b:21->6c:4b:90:ef:36:5a] xxxxxxxxxxx(content of data pack)xxxxxxxxxxxxx
Continuing with next message.
xxxxxxxxxxxxxx(content of data pack)xxxxxxxxxxxxxxxxxxxxxxxxxxx
Incomplete dissection. Probably wrong base encapsulation detected?
```
I wonder if there are requirements for the pcapfile?

**Comment by Aaron911** [comment]
> According to the command line you pasted, I assume, you called the script with **src/** being the current directory? That would explain the error, since the cache and reports folders are one directory level up. Please try to call the `python src/nemetyl_align-segments.py input/dns_ictf2010_deduped-100.pcap` (try a shorter trace for starters) from the repositories base directory.
> 
> I definitely need to improve the documentation.

hi, skleber. Thank u very much for your reply. And I have resolved this following your reply.

**Comment by skleber** [comment]
Glad to hear you could resolve the original issue. I plan to update the documentation and improve parts of the implementation in a few weeks.

Unfortunately, I did not understand your sentence about the folders. If there is something I can help you with, please let me know what you need.

**Comment by Aaron911** [comment]
> Glad to hear you could resolve the original issue. I plan to update the documentation and improve parts of the implementation in a few weeks.
> 
> Unfortunately, I did not understand your sentence about the folders. If there is something I can help you with, please let me know what you need.

Sorry, I did not express it clearly. I have update https://github.com/vs-uulm/nemesys/issues/1#issuecomment-743464893. And I have another question about NEMESYS. I will open a new issue. Thank u agin.

**Comment by Aaron911** [comment]
> Glad to hear you could resolve the original issue. I plan to update the documentation and improve parts of the implementation in a few weeks.
> 
> Unfortunately, I did not understand your sentence about the folders. If there is something I can help you with, please let me know what you need.

Sorry,  I did not express it clearly but it is not a question. I have updated https://github.com/vs-uulm/nemesys/issues/1#issuecomment-743464893. Thank u again.

**Comment by skleber** [comment]
Great. In this case, I will close this issue. Feel free to open another one for a different topic.
