### ISSUE TITLE
reportWriter.writeReport: ValueError: 1.0 is not in list

### ISSUE THREAD

**Issue by techge** [vs-uulm/nemesys#12]
While using the reportWriter module, there seems to be some kind of problem that I currently can not figure out and I am hoping that you may see what the problems is here.

What I am using is [this script](https://github.com/techge/l2pre/blob/3f630c692b6717ce0a24a7fb6aee0c95d00e97a5/src/l2pre_fms.py) in via the command you can see in the snippet below.

```
$ ./src/l2pre_fms.py --no-tunnel input/ethernet/test1.pcapng

...

Write report to reports
Traceback (most recent call last):
  File "./src/l2pre_fms.py", line 116, in <module>
    main(args)
  File "./src/l2pre_fms.py", line 85, in main
    reportWriter.writeReport(fms, inference_runtime, specimens, comparator, inference_title)
  File "/l2pre/src/nemere/utils/reportWriter.py", line 136, in writeReport
    meanI = scoreSorted.index(scoreStats[1])
ValueError: 1.0 is not in list
```

It *is* possible that this is provoked by [my own changes in nemere](https://github.com/vs-uulm/nemesys/compare/master...techge:l2pre), but I do not see how they affect this specific module. So if this is only my stupidity, I am sorry.

It is a bit difficult for me to follow the reasoning behind the single steps involved [here](https://github.com/vs-uulm/nemesys/blob/4087944180b55f2e33f474b4785c03755f42a858/src/nemere/utils/reportWriter.py#L131) where things break...

**Comment by techge** [comment]
I just comment [these lines](https://github.com/vs-uulm/nemesys/blob/4087944180b55f2e33f474b4785c03755f42a858/src/nemere/utils/reportWriter.py#L131-L143) for now. As far as I can see, they are used to export a tikzfile. I currently do not need this... If you like to debug this part, let me know.

**Comment by skleber** [comment]
I added a condition to catch incidents like this. This should solve the issue.
