### ISSUE TITLE
Could you update the tshark into newest version (3.4.5)? 

### ISSUE THREAD

**Issue by Liuyh-dianfeng** [vs-uulm/nemesys#2]
I meet some problems in installing tshark2.6.8 or lower versions. And it seems that tshark3.4.5 is not compatible. Anyway, NEMESYS still works and inspires me. But, NEMETYL cannot work individually without tshark.

**Comment by Liuyh-dianfeng** [comment]
Finally, I successfully installed tshark2.6.8. But the Dissection is still incomplete. Did I miss any step?

**Comment by skleber** [comment]
I will look into the issue.

An internal version of the code is tested with tshark 3.2.3/5 and should also work with newer versions. This requires some backporting from code I cannot release at the moment, so I will need at least some days worth of time to clean up my repository.

NEMETYL in principle should work without tshark, but the sample script in the repository may very well have unintended dependencies. I should fix that independently of the tshark compatibility issue.

**Comment by Liuyh-dianfeng** [comment]
Thank you! I have successfully reproduced NEMETYL in the provided dataset. However, in my own dataset, the "Dissection is incomplete". How do I skip the tshark's results (which is the "comparator"  in the code) and just get the clustering results of NEMETYL?

**Comment by Liuyh-dianfeng** [comment]
Thank you! I know how to use it.

**Comment by skleber** [comment]
Should be fixed by 679a2ea

There may still be a warning about the tshark version. You can ignore it, but I would very much like your feedback on whether you experience any errors. If tshark parsing works flawlessly, please report the version you use, then I can update the list of tested tsharks and the warning will go away.
