### ISSUE TITLE
Slow distance calculator execution time.

### ISSUE THREAD

**Issue by phillips96** [vs-uulm/nemesys#23]
Hello,

I noticed there's a `TODO` in `inference/templates.py` regarding the number of calls to `embedSegment` and scipy's `cdist` operation. I'm not sure if you're accepting PR's but I took a stab at it yesterday out of necessity. 

Here's one such example of the improvements. Note the results are identical. 
```
.... 34523895 segment pairs in 704.63 seconds. # Old
.... 34523895 segment pairs in 149.37 seconds. # New
```
That was on a single worker, and with `parallelDistanceCalc` enabled it went from 310 seconds to 125.

For the most part, I just implemented the changes that had been suggested, such that `embedSegment` now takes all of the `outersegs` and makes one `cdist` call instead of one call for each `oseg` in `outersegs`. 

If you'd be happy for me to make the PR, i'll make one which implements the following new functions or overrides the old based on your preference;

- `_outerloop`
- `embedSegmentGroup`
- `__prepareValuesMatrices`

Thanks :)

**Comment by skleber** [comment]
Sorry for the long latency of this answer. In any case a PR would be greatly appreciated! :+1:

**Comment by skleber** [comment]
Feel free to provide a PR anytime.
