### ISSUE TITLE
Location of PCA code

### ISSUE THREAD

**Issue by 2000lyn** [vs-uulm/nemesys#27]
Excuse me, could you tell me where are the PCA code files ? I can't find them

**Comment by skleber** [comment]
Thank you for pointing this out. I have missed to include the example code in the release. I will fix this as soon as I have time.

Until then, you can find the function performing the PCA refinement here: https://github.com/vs-uulm/nemesys/blob/92d65ce25429a92a6a50ebf46a78af886b36b6fe/src/nemere/inference/segmentHandler.py#L755

**Comment by skleber** [comment]
With the current release this issue should be fixed.
