### ISSUE TITLE
New pcaps in input

### ISSUE THREAD

**Issue by techge** [vs-uulm/nemesys#6]
I am not sure if you might pushed some more pcaps than anticipated in input. Can you have a look into it? This looks like internal test data...

**Comment by skleber** [comment]
There are some PCAPs that are unused in any of the current evaluation scripts, thats right. However, non of the files contains private data and anybody is free to experiment with them. Only problem is I think, its not well documented which traces I used for the papers. I need to put this into some document in the repository: 

I used the traces in input/deduped-orig/ prepared from by src/prep_deduplicate-trace.py as described in input/Sources.md

Do you have any specific concerns about any trace or any other question regarding the traces?

**Comment by techge** [comment]
> Do you have any specific concerns about any trace or any other question regarding the traces?

Not at all, some notes and traces did just look somewhat "internal" to me and therefore I just wanted to make sure that they did not get into the repo by accident. I don't see any problem in the folder content generally.
